### ISSUE TITLE
Please release to Maven Central

### ISSUE THREAD

**Issue by ooxi** [yawkat/cowsay#1]
Hi,

could you please release an artifact to Maven Central?

-- ooxi

**Comment by yawkat** [comment]
This project unfortunately depends on bukkit, so it won't be useful on central.

I have just deployed it to https://mvn.yawk.at , though.

**Comment by ooxi** [comment]
Would you merge a pull request splitting cowsay into two artifacts? One for the basic functionallity and one shaded with all dependencies like bukkit?

**Comment by yawkat** [comment]
What kind of basic functionality do you require? Shading is not the issue here.

**Comment by ooxi** [comment]
Well I'd just like to to call `Cowsay.cowsay("Hello")` and get an formatted output to a `PrintStream`/`PrintWriter` :)

**Comment by yawkat** [comment]
Released on central. Thank you.
